---
timezone: America/Puerto_Rico
markdown: kramdown
name: George Perez-Marrero
author: George Perez-Marrero
url: https://titanpointe.org
email: george@perez-marrero.com
permalink: blog/:year/:month/:title
host: 0.0.0.0
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
  - script/
include:
  - /.well-known/
description: "Computer science undergrad at the University of Puerto Rico at Mayag&uuml;ez. Interested in macOS, iOS, software development, and photography."
highligther: rouge
plugins:
    - jekyll-email-protect
sass:
    sass_dir: _sass
    style: compressed
