---
timezone: America/Puerto_Rico
markdown: kramdown
name: TITANPOINTE
author: George Perez-Marrero
url: https://titanpointe.org
email: george@perez-marrero.com
permalink: :year/:month/:title/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
  - .vagrant/
  - Vagrantfile
description: "Computer science undergrad at the University of Puerto Rico at Mayag&uuml;ez. Interested in macOS, iOS, and software development."
highligther: rouge
plugins:
    - jekyll-email-protect
sass:
    sass_dir: _scss
    style: compressed
