---
description: "Software engineer."
timezone: America/Puerto_Rico
markdown: kramdown
highligther: rouge
title: George Perez Marrero
author: George Perez Marrero
url: https://georgeperez.dev
email: george@perez-marrero.com
repository: georgeperez/georgeperez.dev
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
  - static.json
sass:
  sass_dir: _scss
  style: compressed
