---
markdown: kramdown
url: http://george.perez-marrero.com
permalink: pretty
description: "Not the comic book artist. CS undergrad at UPRM."
highligther: rouge
timezone: America/Puerto_Rico
google_analytics_id: UA-40381065-2
email: george.perez.marrero@gmail.com
github: [metadata]
repository: https://github.com/georgeperez/georgeperez.github.io
gems: 
  - jekyll-sitemap
