---
timezone: America/Puerto_Rico
markdown: kramdown
name: George Perez-Marrero
author: George Perez-Marrero
url: https://george.perez-marrero.com
email: george@perez-marrero.com
permalink: :year/:month/:title
description: "Not the comic book artist. CS undergrad at UPRM."
highligther: rouge
include: [".well-known"]
gems:
    - jekyll-sitemap
    - jekyll-email-protect
sass:
    sass_dir: _sass
    style: compressed
