---
description: "Software engineer."
timezone: America/Puerto_Rico
markdown: kramdown
highligther: rouge
title: Titanpointe
author: George Perez Marrero
url: https://titanpointe.org
email: george@perez-marrero.com
repository: georgeperez/titanpointe.org
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
  - static.json
sass:
  sass_dir: _scss
  style: compressed
