---
title: George Perez-Marrero
markdown: kramdown
permalink: pretty
highligther: rouge
timezone: America/Puerto_Rico
google_analytics_id: UA-40381065-2
email: george@georgeperezmarrero.com
excerpt_separator: <!--more-->
