---
markdown: kramdown
author: George Perez-Marrero
url: http://georgeperezmarrero.com
permalink: pretty
description: "Not the comic book artist. Ranting since 1996."
highligther: rouge
timezone: America/Puerto_Rico
google_analytics_id: UA-40381065-2
email: george.perez.marrero@gmail.com
github: [metadata]
repository: https://github.com/georgeperez/georgeperez.github.io
gems: 
  - jekyll-sitemap
  