---
description: "Computer science undergrad at the University of Puerto Rico at Mayag&uuml;ez. Interested in macOS, iOS, and software development."
timezone: America/Puerto_Rico
markdown: kramdown
highligther: rouge
title: titanpointe
author: George Perez-Marrero
url: https://titanpointe.org
email: george@perez-marrero.com
repository: georgeperez/titanpointe.org
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
  - static.json
plugins:
  - "jekyll-github-metadata"
sass:
  sass_dir: _scss
  style: compressed
