---
markdown: kramdown
author: George Perez-Marrero
url: https://george.perez-marrero.com/
email: george.perez.marrero@gmail.com
permalink: /:year/:month/:title.html
description: "Not the comic book artist. CS undergrad at UPRM."
highligther: rouge
timezone: America/Puerto_Rico
google_analytics_id: UA-40381065-2
github: [metadata]
repository: https://github.com/georgeperez/george.perez-marrero/
gems: 
  - jekyll-sitemap
  - jekyll-email-protect
